name: Documentation Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get install doxygen

      - name: Generate Docs with Doxygen
        run: doxygen Doxyfile

      - name: Commit and push docs to autogen-docs branch
        run: |
          git checkout -b autogen-docs || git checkout autogen-docs
          git add html/
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -m "docs: Automated documentation update"
          git push --force --set-upstream origin autogen-docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./html
          publish_branch: gh-pages
